on: pull_request

# Checkstyle uses google_checks.xml by default.
# google_checks.xml is defined in https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
# checkstyle documentation is at https://checkstyle.org/checks.html
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
